INSERT INTO "PUBLIC"."CENTREINTERET"
( "IDINTERET", "NOMINTERET" )
VALUES (1 , 'C#')

INSERT INTO "PUBLIC"."CENTREINTERET"
( "IDINTERET", "NOMINTERET" )
VALUES (2 , 'J2EE')

INSERT INTO "PUBLIC"."CENTREINTERET"
( "IDINTERET", "NOMINTERET" )
VALUES (3 , 'VB.NET')

INSERT INTO "PUBLIC"."CENTREINTERET"
( "IDINTERET", "NOMINTERET" )
VALUES (4 , 'Administration Oracle ')

INSERT INTO "PUBLIC"."CENTREINTERET"
( "IDINTERET", "NOMINTERET" )
VALUES (5 , 'Administration Windows ')